bucket         = "terraform-state-dev-bucket"
key            = "dev/terraform/modules/sagemaker-terraform.tfstate"
dynamodb_table = "terraform-app-dev-statelock"
region         = "us-east-1"
profile        = "default"
